version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000" # Map container port 5000 to host port 5000
    environment:
      - MONGO_URI=mongodb://mongo:27017/mydatabase
      - JWT_SECRET=mySecretKey
      - PORT=5000
    depends_on:
      - mongo

  mongo:
    image: mongo:6
    container_name: mongodb
    ports:
      - "27017:27017" # Map MongoDB port
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data:
